### ISSUE TITLE
[feature] `poll` command

### ISSUE THREAD

**Issue by BrandonWLee** [tnygaming/discord-bot#11]
Something like `.poll <question> <choice1> <choice2>...`
Bot will return a formatted poll, where users could answer using some sort of reactions (like the number emojis)

**Comment by mynameisivan** [comment]
@BrandonWLee one thing you can do is have the bot send the question and listen to emoji reactions as the 'vote' from a person. I'm not sure how to enforce one vote per person (if that is a requirement)

**Comment by BrandonWLee** [comment]
It's probably possible to enforce votes, but I bet the bot will need permission to remove reactions or something.

**Comment by mynameisivan** [comment]
Looks doable, similar bots have been made for role choosing.

https://github.com/peterthehan/discord-reaction-role-bot
